apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: devopssampleservice
  annotations:
    github.com/project-slug: github-mnf-devop/devopssampleservice
spec:
  type: other
  lifecycle: unknown
  owner: guests
